### ISSUE TITLE
为什么我执行mailI()出错 win10企业版64位

### ISSUE THREAD

**Issue by xiaoyiddos** [yangyangwithgnu/bypass_disablefunc_via_LD_PRELOAD#1]
![image](https://user-images.githubusercontent.com/46039468/50322908-39df5a80-0512-11e9-907a-a75a961ed708.png)

**Comment by yangyangwithgnu** [comment]
这种手法的关键点是环境变量 LD_PRELOAD，只有 linux 才有这个变量，不支持 windows。

**Comment by xiaoyiddos** [comment]
我也用centos搭建了,还是不行.

**Comment by xiaoyiddos** [comment]
![image](https://user-images.githubusercontent.com/46039468/50324976-ef171000-051c-11e9-8c3c-f1ba011837cf.png)
权限有问题吗

**Comment by yangyangwithgnu** [comment]
> 我也用centos搭建了,还是不行.

x86 or x64?

**Comment by xiaoyiddos** [comment]
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

64的

**Comment by xiaoyiddos** [comment]
我直接全部默认配置 还是不行.

**Comment by yangyangwithgnu** [comment]
你贴下 phpinfo() 输出中的 disable_functions 和 safe_mode 的内容，文字版，我测试下。

**Comment by xiaoyiddos** [comment]
disable_functions | no value | no value


sql.safe_mode | Off | Off


我是直接yum install php 然后测试的

**Comment by xiaoyiddos** [comment]
大佬可以加个微信交流吗,我也在成都.

**Comment by yangyangwithgnu** [comment]
3297083841，要得，加起聊。

**Comment by xiaoyiddos** [comment]
加你了大神~

**Comment by yangyangwithgnu** [comment]
原因是 SELinux。

你用 apache 身份运行 id，输出 `uid=48(apache) gid=48(apache) groups=48(apache) context=system_u:system_r:httpd_t:s0`，看到最后的 `context=system_u:system_r:httpd_t:s0`没，就是 SELinux 在作祟。

**Comment by Malayke** [comment]
该用户不存在，加不上你啊，我也想研究一下这个漏洞，我之前看到过使用[LD_PRELOAD进行提权的文章](https://touhidshaikh.com/blog/?p=827)，这个方法很棒，能提供下这个环境更详细点的信息吗？

我想虚拟机搭建一个相同的环境，学习一下这种方法。


比如是什么系统 ， PHP是什么版本，除了 disable_function， 还有需要配置之类的

**Comment by yangyangwithgnu** [comment]
> 该用户不存在，加不上你啊，我也想研究一下这个漏洞，我之前看到过使用[LD_PRELOAD进行提权的文章](https://touhidshaikh.com/blog/?p=827)，这个方法很棒，能提供下这个环境更详细点的信息吗？
> 
> 我想虚拟机搭建一个相同的环境，学习一下这种方法。
> 
> 比如是什么系统 ， PHP是什么版本，除了 disable_function， 还有需要配置之类的

那是 QQ 不是微信 ：-）

由于 LD_PRELOAD 的特殊性，既可以用于提权，又能用于绕过 disable_functions 执行命令，我这个 repo. 主要是后者。
